name:  CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: npm ci
      - name:  Run tests
        run: npm run test

  publish:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          # create access token and set to secret @see{@link https://docs.github.com/en/enterprise-server@3.0/github/authenticating-to-github/creating-a-personal-access-token}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: mohammadranjbarz/ci-cd-tutorial
          # Add commit hash to docker image tag @see{@link https://github.com/docker/build-push-action/tree/releases/v1#tag_with_sha}
          tag_with_sha: true
          # Add branch name to docker image tag @see{@link https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref}
          tag_with_ref: true
